project:
  type: website
  output-dir: docs

website:
  title: "Research Tools"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Drift Diffusion Models
        menu:
          - href: ddm/individual.qmd
            text: Individual-Level Models

          - href: ddm/hierarchical.qmd
            text: Hierarchical Models

          - href: ddm/joint.qmd
            text: Joint Neuroimaging Models

format:
  html:
    theme: cosmo
    toc: true